#!/usr/bin/env node

var s3touch = require('./index.js');
var argv = require('minimist')(process.argv.slice(2), {
    boolean: [ 'recursive' ]
});
var s3paths = argv._;
var cache = {};
var topic = null;
var requesterPays = false;
var processed_count = 0;
if (s3paths.length < 1) {
    console.log(s3touch.usage());
    process.exit(1);
}
if (argv.topic === true) {
    console.log(s3touch.usage());
    process.exit(1);
}

function run(err, data) {
    if (err) {
        console.warn(err.toString());
        process.exit(1);
    }
    if (data) {
        console.log('ok - ' + s3paths[0],'removing the prev item');
        s3paths.shift();
    }
    setTimeout(function (){
        if (s3paths.length > 0) {
            processed_count += 1;
            s3touch.touch(s3paths[0], cache, topic, requesterPays, run);
        }
        else{
            console.log('done : processed files : ',processed_count)
        }
    },0)
}

if (argv.topic) topic = argv.topic;
if (argv.requesterpays) requesterPays = true;

if (argv.recursive) {
    s3touch.list(s3paths[0], function(err, list) {
        if (err) {
            console.warn(err.toString());
            process.exit(1);
        }
        s3paths = list;
        run();
    });
} else {
    run();
}
